<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>index</title>
    <link href="/css/home.css" rel="stylesheet"/>
    <script type="text/javascript" src="/js/jquery.js"></script>
    <script type="text/javascript" src="/js/home.js"></script>
</head>
<body>
<input id="upImage" type="file" style="display:none;"/>
<button type="button" id="choosefile">CHOOSE FILE</button>
<button type="button" id="upload">UPLOAD</button>
<p>!!! ...</p>

</body>
</html>